### ISSUE TITLE
Non-UTC timestamps not supported

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/gitlab-artifact-cleanup#1]
```
ValueError: time data '2016-09-30T14:31:09.447-04:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ
```

This happens when GitLab is configured with a non-UTC timezone.

**Comment by JonathonReinhart** [comment]
I hate to add another external dependency, but it looks like `dateutil` is the way to go here:

https://dateutil.readthedocs.io/en/stable/examples.html#parse-examples

**Comment by JonathonReinhart** [comment]
Going to `dateutil` yields the next problem:

```
TypeError can't subtract offset-naive and offset-aware datetimes
```

The solution is to either go to Python 3, or add another external dependency `pytz`:
http://stackoverflow.com/a/25662061/119527

**Comment by wpostma** [comment]
Looking at this situation (python 2.7's utc mess) I'm so glad I mostly work on Python 3!

But I loved that TypeError in 2.7, because it prevents subtle annoying bugs.   I wish they'd add the timezone stuff to python 2.7, goodness me what a mess.
