### ISSUE TITLE
dead gitlab link

### ISSUE THREAD

**Issue by glensc** [JonathonReinhart/gitlab-artifact-cleanup#12]
project says it's moved to gitlab: https://gitlab.com/JonathonReinhart/gitlab-artifact-cleanup

but that link is 404!

ps: i'm coming from https://gitlab.com/gitlab-org/gitlab-ce/issues/5572

**Comment by JonathonReinhart** [comment]
The link you just posted is good for me, and should be the correct URL.  Are you still seeing a 404?

**Comment by glensc** [comment]
yes. the project is not accessible. make it public!

ps: use incognito mode in browser to test yourself

**Comment by JonathonReinhart** [comment]
@glensc Ah, good call. Sorry about that. Thanks for letting me know!
