### ISSUE TITLE
Can not erase artifacts with tool, api changes to python-gitlab perhaps

### ISSUE THREAD

**Issue by wpostma** [JonathonReinhart/gitlab-artifact-cleanup#2]
Perhaps there have been api changes to python-gitlab, when I run the script, I first ran into utc issues, which I had to work around (will be comitted to my fork), then I ran into this:

build.erase() fails, as type ProjectBuild has no such attribute:

```
  File "./gitlab-artifact-cleanup", line 76, in cleanup_project
    build.erase()
AttributeError: 'ProjectBuild' object has no attribute 'erase'

```

I had a quick peek on the docs and that ProjectBuild seems to have a delete which I tried, and I get this instead:

```
            if not self.dry_run:
                build.delete() # used to be erase?

```

That gets me a NotImplemented exception.  Maybe there's another way to delete artifacts now?

**Comment by wpostma** [comment]
WIP Pullrequest (not ready to merge), just shows what I tried:

https://github.com/JonathonReinhart/gitlab-artifact-cleanup/pull/3

**Comment by JonathonReinhart** [comment]
Regarding UTC / timestamps, see #1. I had already pushed the `1-fix-timezone-issues` branch, but forgot about it before merging :innocent: 

See MR #4 - and let me know if you think using `pytz` is better than switching to Py3.

**Comment by JonathonReinhart** [comment]
Regarding `erase()`, [README.md](../blob/master/README.md) indicates:

> python-gitlab - As of at least [d4a24a5c4d](https://github.com/gpocentek/python-gitlab/commit/d4a24a5c4dc54ac03b917723347047e3995afcc9), which is currently unreleased.

You need `python-gitlab` with [my fix (PR 159)](https://github.com/gpocentek/python-gitlab/pull/159).

**Comment by wpostma** [comment]
Thanks for the quick reply! did you really want to move this script to be
Python3-only? It could be python2+3, and I don't mind trying to do a PR for
that if you want.

On Thu, Oct 13, 2016 at 1:38 PM, Jonathon Reinhart <notifications@github.com

**Comment by wpostma** [comment]
I closed my initial messy pr. I will try again with a clean python2 support.

This issue is closed because it was just my failure to READ the README! :-)
